apiVersion: apps/v1
kind: Deployment
metadata:
  name: speeddemon-deployment # Must match deploy.yml 'set image' command
  labels:
    app: speeddemon-app       # Unique ID for this project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: speeddemon-app
  template:
    metadata:
      labels:
        app: speeddemon-app
    spec:
      containers:
      - name: backend
        # Update with your DockerHub ID and 'speeddemon' name
        image: your-dockerhub-user/speeddemon:latest 
        ports:
        - containerPort: 8000
        
        envFrom:
          - secretRef:
              name: app-secrets
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
